Master: false
RemoteAddress: 192.168.68.101
TcpPort: 80
Rules:
    - FilePath: /etc/passwd
      Checks: -p rwxa 
      Key: password
    - FilePath: /etc/shadow
      Checks: -p rwxa 
      Key: password